`Lab. 1` _and_ `Lab. 2` done.
ISUCT/TProgramming_2024 pull request #17
Opened 2024-09-26 22:15 UTC by Egorkin-enabled

**Hello**, Eugenii Sergeevich. I'm Kozlov Egor, student of 2/278 group.
I want to say that I have written all **CodeWars** tasks. Also made **TS** laboratory with **Unit tests**.

At **CodeWars** I've used different languages:

- **C#** as the main one;
- **JS** for some tasks that couldn't be solved different;
- **C** for about of 1/3 tasks &mdash; I'm pointer arithmetic believer!
- **C++** in few tasks where **C** was forbidden. 

Is everything did OK? I'm waiting for a feedback. Thank you and have a nice day!

2024-10-05 07:38 UTC, Egorkin-enabled commented
Hello Eugenii Sergeevich. I have merged your fixes.

2024-10-05 09:04 UTC, Egorkin-enabled commented
Hello again. I have did `Lab 3`. I'll fix `Pull request` header.

2024-10-05 10:14 UTC, jskonst requested changes

2024-10-05 10:14 UTC, jskonst commented on package.json
> +{
этот тоже удаляем

2024-10-05 10:14 UTC, jskonst commented on rpgsaga/saga/.gitignore
> +# Logs
в каталоге выше был gitignore

2024-10-05 10:14 UTC, jskonst commented on rpgsaga/saga/src/lab1/funcs.ts
> +  while (xCurrent < xEnd) {
for ?

2024-10-05 10:14 UTC, jskonst commented on rpgsaga/saga/src/lab1/funcs.ts
> +  for (const index in xes) {
```suggestion
  for (const index of xes) {
```

2024-10-05 10:14 UTC, jskonst commented on rpgsaga/saga/test/lab1/test.spec.ts
> +it('should be empty if end >= start.', () => {
объедините в describe

2024-12-06 21:18 UTC, Egorkin-enabled commented
Hello, Eugeny Sergeevich. I've applied all of the remarks. I hope it's all right.

2024-12-07 10:11 UTC, jskonst commented on rpgsaga/saga/src/lab3/animal.ts
> +    this._name = name;
```suggestion
    this.name = name;
```

2024-12-07 10:12 UTC, jskonst commented on rpgsaga/saga/src/lab3/animal.ts
> +    this._birthDate = birthdate;
```suggestion
    this.birthDate = birthdate;
```

2024-12-07 10:13 UTC, jskonst approved these changes

2024-12-07 10:13 UTC, merged